CREATE TABLE KORISNIK (
    ID SERIAL PRIMARY KEY,
    EMAIL VARCHAR(320) NOT NULL,
    IME VARCHAR(50),
    PREZIME VARCHAR(50),
    PASS CHAR(256) NOT NULL
);

CREATE TABLE DEBATA (
    ID SERIAL PRIMARY KEY,
    NAZIV VARCHAR(100),
    DATUM TIMESTAMP WITHOUT TIME ZONE,
    OPIS TEXT,
    KATEGORIJA INTEGER,
    STAGE INTEGER,
    PRIVATNA BOOLEAN,
    POCETAK TIMESTAMP WITHOUT TIME ZONE,
    KRAJ TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE UCESNICI (
    ID_D INTEGER,
    ID_K INTEGER,
    PRIHVATIO BOOLEAN
    CONSTRAINT FK_UCESNICI_ID_D FOREIGN KEY (ID_D) REFERENCES DEBATA(ID),
    CONSTRAINT FK_UCESNICI_ID_K FOREIGN KEY (ID_D) REFERENCES KORISNIK(ID),
    PRIMARY KEY (ID_D,ID_K)
);

CREATE TABLE PRISUTNI(
    ID_D INTEGER,
    ID_K INTEGER,
     
);


